"""Dean id and head id become unique in faculties and departements tabler

Revision ID: 3eced9ac9efc
Revises: 5839c3e629a8
Create Date: 2021-03-04 07:56:45.577452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eced9ac9efc'
down_revision = '5839c3e629a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'departements', ['head_id'])
    op.create_unique_constraint(None, 'faculties', ['dean_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculties', type_='unique')
    op.drop_constraint(None, 'departements', type_='unique')
    # ### end Alembic commands ###
