"""add new field of code in users table

Revision ID: b2f4e9d4f793
Revises: d493de0165ae
Create Date: 2021-05-07 03:51:17.368950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f4e9d4f793'
down_revision = 'd493de0165ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('code', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'code')
    # ### end Alembic commands ###
