"""add new field of is_validated on users table

Revision ID: d493de0165ae
Revises: 12bdbbbb4903
Create Date: 2021-05-05 06:40:02.806759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd493de0165ae'
down_revision = '12bdbbbb4903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_validated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_validated')
    # ### end Alembic commands ###
