"""Renaming departements tabler from dean_id to head_id

Revision ID: e251ea7bcadb
Revises: 6e1d250eda67
Create Date: 2021-03-04 03:11:59.265753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e251ea7bcadb'
down_revision = '6e1d250eda67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departements', sa.Column('head_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_departement_dean', 'departements', type_='foreignkey')
    op.create_foreign_key('fk_departement_head', 'departements', 'users', ['head_id'], ['id'])
    op.drop_column('departements', 'dean_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departements', sa.Column('dean_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_departement_head', 'departements', type_='foreignkey')
    op.create_foreign_key('fk_departement_dean', 'departements', 'users', ['dean_id'], ['id'])
    op.drop_column('departements', 'head_id')
    # ### end Alembic commands ###
